// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://woriqoefmnyeuglohgny.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indvcmlxb2VmbW55ZXVnbG9oZ255Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk4NTY0NzUsImV4cCI6MjA3NTQzMjQ3NX0.mUeEUzLxBeqGxO2uhJoOMJh41mi7A2KOEkWHvLuxTPw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});